# CONFIGSERVER YML
server:
  port: 8888
spring:
  application:
    name: configserver
  profiles:
    active: git # native # non voglio piu' usare quella in locale'
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/sntngl96/microservices02-configserver.git"
          default-label: main
          timeout: 5
          clone-on-start: true #clona il remoto in locale all'avvio
          force-pull: true #fa sempre il pull dopo le modifiche
          #search-locations: "classpath:/config" #mi serve solo con il native